"""
Daily Market Newsletter - Main Runner

Usage:
    python main.py              # Run once (generate today's digest)
    python main.py --bot        # Run Telegram bot (commands + daily schedule)
    python main.py --schedule   # Run on schedule only (10AM PT daily)
    python main.py --test       # Dry run with mock data
"""

import argparse
import sys
from datetime import datetime

from config import DEEP_ANALYSIS_ENABLED, DEEP_ANALYSIS_MAX_TICKERS, DEEP_ANALYSIS_TIMEOUT
from market_data import get_top_movers, enrich_sector_info, filter_movers_by_size, fetch_blue_chips, fetch_watchlist, get_last_trading_day, is_market_open
from news_fetcher import get_news_for_movers
from llm_analyzer import analyze_movers


def generate_digest(limit: int = 10) -> str:
    """Full pipeline: movers → news → analysis → formatted digest."""
    print(f"\n{'='*60}")
    print(f"  Market Digest - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"{'='*60}\n")

    # Step 1: Get top movers + blue chips + watchlist
    print("[1/6] Fetching top movers...")
    movers = get_top_movers(limit)
    movers = enrich_sector_info(movers)
    movers = filter_movers_by_size(movers)

    gainers_count = len(movers.get("gainers", []))
    losers_count = len(movers.get("losers", []))
    print(f"      Found {gainers_count} gainers, {losers_count} losers")

    if not gainers_count and not losers_count:
        return "⚠️ No market data available. Check API keys and market hours."

    # Step 1b: Blue chips + watchlist
    print("[1.5/6] Fetching blue chips + watchlist...")
    blue_chips = fetch_blue_chips(min_change_pct=1.0)
    watchlist = fetch_watchlist()

    # Dedupe: remove watchlist/blue chip tickers already in top movers
    existing_tickers = {m["ticker"] for d in ["gainers", "losers"] for m in movers[d]}
    blue_chips = [b for b in blue_chips if b["ticker"] not in existing_tickers]
    watchlist = [w for w in watchlist if w["ticker"] not in existing_tickers]

    # Add to movers for news fetching (as separate lists)
    movers["blue_chips"] = blue_chips
    movers["watchlist"] = watchlist

    extra_count = len(blue_chips) + len(watchlist)
    if extra_count:
        print(f"      Added {len(blue_chips)} blue chips, {len(watchlist)} watchlist")

    # Step 2: Fetch news
    total_tickers = gainers_count + losers_count + extra_count
    print("[2/6] Fetching related news...")
    news = get_news_for_movers(movers, limit_per_ticker=3)
    tickers_with_news = len([t for t, a in news.items() if a])
    print(f"      Found news for {tickers_with_news}/{total_tickers} tickers")

    # Step 3: LLM analysis
    print("[3/6] Analyzing with LLM...")
    digest = analyze_movers(movers, news)

    # Step 3.5: Deep analysis (TradingAgents)
    deep_section = ""
    if DEEP_ANALYSIS_ENABLED:
        print("[4/6] Running deep analysis (TradingAgents)...")
        try:
            from deep_analyzer import run_all_deep_analyses
            deep_section = run_all_deep_analyses(
                movers, news,
                max_tickers=DEEP_ANALYSIS_MAX_TICKERS,
                timeout=DEEP_ANALYSIS_TIMEOUT,
            )
        except Exception as e:
            print(f"[deep] Skipped due to error: {e}")
    else:
        print("[4/6] Deep analysis disabled, skipping")

    # Step 5: Format output
    print("[5/6] Formatting digest...")
    if is_market_open():
        # Market is live — show today's date in the header
        trading_date = datetime.now().strftime("%B %d, %Y")
        header = f"📊 **Daily Market Digest** — {trading_date}\n\n"
    else:
        trading_day = get_last_trading_day()
        trading_date = datetime.strptime(trading_day, "%Y-%m-%d").strftime("%B %d, %Y")
        header = f"📊 **Daily Market Digest** — {trading_date} (market closed)\n\n"
    footer = "\n\n---\n_Generated by Market News Bot_"

    full_digest = header + digest + deep_section + footer
    print("[6/6] Done!")
    print(f"\n✅ Digest ready ({len(full_digest)} chars)")

    return full_digest


def format_for_telegram(text: str) -> list[str]:
    """Convert markdown to Telegram HTML and split into chunks under 4000 chars."""
    import re

    html = text
    # Convert Markdown bold **text** to HTML <b>text</b>
    html = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", html)
    # Convert ## headers to bold lines
    html = re.sub(r"^##\s*(.+)$", r"<b>\1</b>", html, flags=re.MULTILINE)

    # Split on paragraph boundaries to avoid breaking HTML tags mid-tag
    if len(html) <= 4000:
        return [html] if html else [""]

    chunks = []
    current = ""
    for paragraph in html.split("\n\n"):
        candidate = (current + "\n\n" + paragraph) if current else paragraph
        if len(candidate) > 4000:
            if current:
                chunks.append(current)
            current = paragraph[:4000] if len(paragraph) > 4000 else paragraph
        else:
            current = candidate
    if current:
        chunks.append(current)
    return chunks if chunks else [""]


def format_compact_summary(digest: str) -> str:
    """Parse full LLM digest into compact one-line-per-ticker format.

    Extracts lines matching the SYSTEM_PROMPT pattern:
        ### ▲ TICKER (+X.XX%) $XXX.XX | Vol: XXM — Catalyst type

    Returns lines like:
        ▲ NVDA +8.5% | GPU demand surge on data center contracts
        ▼ XOM -3.2% | Falling oil prices on OPEC output increase

    Returns empty string if no matching lines are found.
    """
    import re

    pattern = re.compile(
        r"^#{2,3}\s*(▲|▼)\s+([A-Z][A-Z0-9.\-]{0,8})\s+\(([+-]?\d+\.?\d*)%\)[^\n]*?—\s*(.+?)$",
        re.MULTILINE,
    )
    lines = []
    for m in pattern.finditer(digest):
        arrow, ticker, pct, catalyst = m.groups()
        sign = "+" if not pct.startswith("-") and not pct.startswith("+") else ""
        lines.append(f"{arrow} {ticker} {sign}{pct}% | {catalyst.strip()}")

    return "\n".join(lines)


def send_telegram(text: str) -> bool:
    """Send digest via Telegram (if configured)."""
    from config import TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID

    if not TELEGRAM_BOT_TOKEN or TELEGRAM_BOT_TOKEN.startswith("your_"):
        print("[telegram] Not configured, skipping...")
        return False

    import requests

    try:
        chunks = format_for_telegram(text)

        for chunk in chunks:
            resp = requests.post(
                f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage",
                json={
                    "chat_id": TELEGRAM_CHAT_ID,
                    "text": chunk,
                    "parse_mode": "HTML",
                    "disable_web_page_preview": True,
                },
                timeout=15,
            )
            resp.raise_for_status()

        print("[telegram] ✅ Digest sent!")
        return True

    except Exception as e:
        print(f"[telegram] ❌ Send failed: {e}")
        return False


def run_scheduled():
    """Run on a daily schedule at 10AM Pacific Time."""
    from apscheduler.schedulers.blocking import BlockingScheduler
    from apscheduler.triggers.cron import CronTrigger

    scheduler = BlockingScheduler()

    # 10:00 AM Pacific Time (America/Los_Angeles)
    trigger = CronTrigger(
        hour=10,
        minute=0,
        timezone="America/Los_Angeles",
    )

    def job():
        digest = generate_digest()
        print("\n" + digest)
        send_telegram(digest)

    scheduler.add_job(job, trigger, id="daily_digest")
    print("⏰ Scheduler started — next run at 10:00 AM PT")
    print("   Press Ctrl+C to stop\n")

    try:
        scheduler.start()
    except (KeyboardInterrupt, SystemExit):
        print("\n👋 Scheduler stopped")


def run_test():
    """Dry run with mock data (no API calls)."""
    from llm_analyzer import _fallback_summary

    mock_movers = {
        "gainers": [
            {"ticker": "NVDA", "name": "NVIDIA Corp", "price": 950.50,
             "change_pct": 8.5, "change_abs": 74.5, "volume": 85_000_000,
             "sector": "tech", "sector_raw": "Technology"},
            {"ticker": "AAPL", "name": "Apple Inc", "price": 228.30,
             "change_pct": 3.2, "change_abs": 7.08, "volume": 45_000_000,
             "sector": "tech", "sector_raw": "Technology"},
            {"ticker": "LLY", "name": "Eli Lilly", "price": 820.15,
             "change_pct": 5.1, "change_abs": 39.80, "volume": 12_000_000,
             "sector": "healthcare", "sector_raw": "Healthcare"},
        ],
        "losers": [
            {"ticker": "XOM", "name": "Exxon Mobil", "price": 105.20,
             "change_pct": -3.2, "change_abs": -3.48, "volume": 22_000_000,
             "sector": "energy", "sector_raw": "Energy"},
            {"ticker": "META", "name": "Meta Platforms", "price": 510.80,
             "change_pct": -2.8, "change_abs": -14.70, "volume": 30_000_000,
             "sector": "tech", "sector_raw": "Technology"},
        ],
    }
    mock_news = {
        "NVDA": [{"title": "NVIDIA announces Blackwell Ultra GPU", "description": "Next-gen architecture...",
                   "source": "reuters", "url": "#", "published_at": "2026-04-04", "sentiment": 0.85}],
        "AAPL": [{"title": "Apple Vision Pro 2 sales beat expectations", "description": "Strong demand...",
                   "source": "cnbc", "url": "#", "published_at": "2026-04-04", "sentiment": 0.6}],
        "LLY": [{"title": "Eli Lilly weight-loss drug shows Phase 3 results", "description": "Trial data...",
                  "source": "seekingalpha", "url": "#", "published_at": "2026-04-04", "sentiment": 0.9}],
        "XOM": [],
        "META": [{"title": "EU regulators announce new AI Act enforcement", "description": "Fines possible...",
                   "source": "reuters", "url": "#", "published_at": "2026-04-04", "sentiment": -0.4}],
    }

    print("\n🧪 TEST MODE — using mock data\n")
    digest = _fallback_summary(mock_movers, mock_news)
    header = f"📊 **Daily Market Digest** — {datetime.now().strftime('%B %d, %Y')} (TEST)\n\n"
    print(header + digest)


def run_deep_only(ticker: str):
    """Run deep analysis on a single ticker (for testing)."""
    from deep_analyzer import run_deep_analysis, format_deep_analysis_section, TRADINGAGENTS_AVAILABLE

    if not TRADINGAGENTS_AVAILABLE:
        print("ERROR: TradingAgents is not installed.")
        print("Install it with: pip install /path/to/TradingAgent/")
        sys.exit(1)

    from market_data import get_last_trading_day, is_market_open

    if is_market_open():
        trade_date = datetime.now().strftime("%Y-%m-%d")
    else:
        trade_date = get_last_trading_day()

    print(f"\nDeep Analysis: {ticker} on {trade_date}")
    print("=" * 50)

    result = run_deep_analysis(ticker, trade_date, timeout=DEEP_ANALYSIS_TIMEOUT)
    if result:
        print(f"\nDecision: {result['decision']}")
        print(f"\nFundamentals: {result['fundamentals_report']}")
        print(f"Sentiment: {result['sentiment_report']}")
        print(f"News: {result['news_report']}")
        print(f"Technical: {result['market_report']}")
        print(f"Risk: {result['risk_assessment']}")
        print("\n--- Telegram preview ---")
        print(format_deep_analysis_section([result]))
    else:
        print("Analysis failed. Check logs above for details.")


def main():
    parser = argparse.ArgumentParser(description="Daily Market Newsletter Bot")
    parser.add_argument("--schedule", action="store_true", help="Run on daily schedule (10AM PT)")
    parser.add_argument("--bot", action="store_true", help="Run Telegram bot (commands + daily schedule)")
    parser.add_argument("--test", action="store_true", help="Dry run with mock data")
    parser.add_argument("--deep-only", metavar="TICKER", help="Run deep analysis on a single ticker")
    parser.add_argument("--limit", type=int, default=10, help="Number of movers (default: 10)")
    args = parser.parse_args()

    if args.deep_only:
        run_deep_only(args.deep_only.upper())
    elif args.test:
        run_test()
    elif args.bot:
        from telegram_bot import run_bot
        run_bot()
    elif args.schedule:
        run_scheduled()
    else:
        digest = generate_digest(args.limit)
        print("\n" + digest)
        send_telegram(digest)


if __name__ == "__main__":
    main()
