#!/usr/bin/env python3
"""Preview — or test-send — the email rendering of a digest.

Runs a digest through the same ``markdown_to_html()`` the email delivery path
uses and writes the result to an HTML file you can open in a browser. With
``--send`` it also calls the real ``send_email()`` (using EMAIL_*/SMTP_* from
your .env) so you can verify an actual delivery end to end.

Usage:
    python scripts/preview_email.py                     # built-in sample → email_preview.html
    python scripts/preview_email.py --out /tmp/x.html   # custom output path
    python scripts/preview_email.py --send              # really send it via SMTP (needs .env)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from newsletter.email_sender import _subject_from_digest, markdown_to_html, send_email

SAMPLE_DIGEST = """\
📊 **Daily Market Digest** — June 03, 2026

## Market summary
Tech **led gains** on strong earnings while energy lagged amid inventory builds.

## 🖥️ Tech
### ▲ NVDA (NVIDIA) (+8.50%) $950.50 | Vol: 85M — Product launch
NVIDIA announced its Blackwell Ultra GPU architecture targeting AI workloads.
Analysts at https://example.com/nvda-note raised price targets.

### ▲ AAPL (Apple) (+3.20%) $228.30 | Vol: 45M — Product demand
Vision Pro 2 pre-orders exceeded analyst expectations.

## ⚡ Energy
### ▼ XOM (Exxon) (-3.20%) $105.20 | Vol: 22M — Macro
Oil prices declined on higher-than-expected EIA inventory builds.

---
_Generated by Market News Bot_
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Preview / test-send digest email rendering")
    parser.add_argument("--out", default="email_preview.html", help="Output HTML file path")
    parser.add_argument(
        "--send",
        action="store_true",
        help="Actually send the sample digest via send_email() using .env SMTP config",
    )
    args = parser.parse_args()

    subject = _subject_from_digest(SAMPLE_DIGEST)
    html = markdown_to_html(SAMPLE_DIGEST)

    out = Path(args.out)
    out.write_text(html, encoding="utf-8")
    print(f"Subject: {subject}")
    print(f"HTML written to: {out.resolve()} ({len(html)} chars)")

    if args.send:
        print("\nSending sample digest via SMTP (needs EMAIL_ENABLED + SMTP_* in .env)...")
        ok = send_email(SAMPLE_DIGEST)
        raise SystemExit(0 if ok else 1)


if __name__ == "__main__":
    main()
