"""Core newsletter pipeline — fetch → news → analyze → format."""

from datetime import datetime

from newsletter.config import DEEP_ANALYSIS_ENABLED, DEEP_ANALYSIS_MAX_TICKERS, DEEP_ANALYSIS_TIMEOUT
from newsletter.market_data import (
    get_top_movers,
    enrich_sector_info,
    filter_movers_by_size,
    fetch_blue_chips,
    fetch_watchlist,
    get_last_trading_day,
    is_market_open,
)
from newsletter.news import get_news_for_movers
from newsletter.digest import analyze_movers
from newsletter.moving_averages import fetch_trend_states, format_trend_section


def generate_digest(limit: int = 10) -> str:
    """Full pipeline: movers → news → analysis → formatted digest."""
    print(f"\n{'='*60}")
    print(f"  Market Digest - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"{'='*60}\n")

    # Step 1: Get top movers + blue chips + watchlist
    print("[1/6] Fetching top movers...")
    movers = get_top_movers(limit)
    movers = enrich_sector_info(movers)
    movers = filter_movers_by_size(movers)

    gainers_count = len(movers.get("gainers", []))
    losers_count = len(movers.get("losers", []))
    print(f"      Found {gainers_count} gainers, {losers_count} losers")

    if not gainers_count and not losers_count:
        return "⚠️ No market data available. Check API keys and market hours."

    # Step 1b: Blue chips + watchlist
    print("[1.5/6] Fetching blue chips + watchlist...")
    blue_chips = fetch_blue_chips(min_change_pct=1.0)
    watchlist = fetch_watchlist()

    # Dedupe: remove watchlist/blue chip tickers already in top movers
    existing_tickers = {m["ticker"] for d in ["gainers", "losers"] for m in movers[d]}
    blue_chips = [b for b in blue_chips if b["ticker"] not in existing_tickers]
    watchlist = [w for w in watchlist if w["ticker"] not in existing_tickers]

    movers["blue_chips"] = blue_chips
    movers["watchlist"] = watchlist

    extra_count = len(blue_chips) + len(watchlist)
    if extra_count:
        print(f"      Added {len(blue_chips)} blue chips, {len(watchlist)} watchlist")

    # Step 2: Fetch news
    total_tickers = gainers_count + losers_count + extra_count
    print("[2/6] Fetching related news...")
    news = get_news_for_movers(movers, limit_per_ticker=3)
    tickers_with_news = len([t for t, a in news.items() if a])
    print(f"      Found news for {tickers_with_news}/{total_tickers} tickers")

    # Step 3: LLM analysis
    print("[3/6] Analyzing with LLM...")
    digest = analyze_movers(movers, news)

    # Step 3.4: Trend snapshot (QQQ/SPY vs 200-day SMA)
    print("[3.5/6] Fetching trend snapshot...")
    trend_section = ""
    try:
        trend_states = fetch_trend_states()
        if trend_states:
            trend_section = "\n\n" + format_trend_section(trend_states)
            print(f"      Got states for {[s.ticker for s in trend_states]}")
        else:
            print("      No trend states available")
    except Exception as e:
        print(f"      Trend snapshot failed: {e}")

    # Step 3.5: Deep analysis (TradingAgents)
    deep_section = ""
    if DEEP_ANALYSIS_ENABLED:
        print("[4/6] Running deep analysis (TradingAgents)...")
        try:
            from newsletter.deep_analysis import run_all_deep_analyses
            deep_section = run_all_deep_analyses(
                movers, news,
                max_tickers=DEEP_ANALYSIS_MAX_TICKERS,
                timeout=DEEP_ANALYSIS_TIMEOUT,
            )
        except Exception as e:
            print(f"[deep] Skipped due to error: {e}")
    else:
        print("[4/6] Deep analysis disabled, skipping")

    # Step 5: Format output
    print("[5/6] Formatting digest...")
    if is_market_open():
        trading_date = datetime.now().strftime("%B %d, %Y")
        header = f"📊 **Daily Market Digest** — {trading_date}\n\n"
    else:
        trading_day = get_last_trading_day()
        trading_date = datetime.strptime(trading_day, "%Y-%m-%d").strftime("%B %d, %Y")
        header = f"📊 **Daily Market Digest** — {trading_date} (market closed)\n\n"
    footer = "\n\n---\n_Generated by Market News Bot_"

    full_digest = header + digest + trend_section + deep_section + footer
    print("[6/6] Done!")
    print(f"\n✅ Digest ready ({len(full_digest)} chars)")

    return full_digest
